### PR TITLE
updated changelog

### PR DESCRIPTION
**Pull request by joefitter**

### CODE REVIEW

**Comment by joefitter** [comment]
@JoeChapman

**Comment by easternbloc** [comment]
What about version 9? And wasn't there an 8.1?

**Comment by joefitter** [comment]
@JoeChapman is on 9

**Comment by easternbloc** [comment]
An I imagining there was an 8.1?

**Comment by joefitter** [comment]
8.1 will be after 🍔

**Comment by easternbloc** [comment]
🆗

**Comment by joefitter** [comment]
ah no I lie - there is no 8.1

**Pull request merged**
