### PR TITLE
Updated depenedencies to get latest hof-controllers - v1.0.1

### PR DESCRIPTION
**Pull request by joefitter**

### CODE REVIEW

**Comment by joefitter** [comment]
@easternbloc @daniel-ac-martin @JoeChapman updated shrinkwrap

**Comment by JoeChapman** [comment]
LGTM @easternbloc @daniel-ac-martin

**Comment by JoeChapman** [comment]
LGTM @bendiggle @gxxm can you just check that this is not stoopid?

**Comment by bendiggle** [comment]
LGTM!

**Pull request merged**
