### PR TITLE
updated hmpo-frontend-toolkit and hmpo-template-mixins to 4.2.0

### PR DESCRIPTION
**Pull request by joefitter**

### CODE REVIEW

**Comment by joefitter** [comment]
@UKHomeOffice/hof can I get a couple of 👍 's please?

**Comment by daniel-ac-martin** [comment]
LGTM.

Might be worth waiting for the new elements before publishing though. (Unless someone desperately needs a new HOF.)

**Comment by daniel-ac-martin** [comment]
https://github.com/UKHomeOffice/passports-frontend-toolkit/pull/46 if anyone is interested.

**Comment by joefitter** [comment]
Would be good to publish as soon as we can as I have a truck load of tickets that were waiting on that last PR

**Comment by joefitter** [comment]
@UKHomeOffice/hof this will need a major bump when merged as there was a potentially breaking change to frontend toolkit

**Comment by easternbloc** [comment]
HOF will need a major version bump.

You also need to update the shrinkwrap.

Or do you want me to do that?

**Comment by joefitter** [comment]
@easternbloc on the branch or to master after merged?

**Comment by joefitter** [comment]
also @easternbloc post merge we should bump by updating master locally then running 

``` bash
$ npm version major; git push origin master --tags
```

currently we aren't pushing tags to GH

**Comment by joefitter** [comment]
@easternbloc @JoeChapman getting the following error when trying to run shrinkwrap:

``` bash
peer invalid: estraverse@*, required by estraverse-fb@1.3.1
```

**Comment by joefitter** [comment]
@JoeChapman @easternbloc shrinkwrap updated - can we merge and bump please?

**Comment by JoeChapman** [comment]
Do we need to get a thumbs up from @gavboulton ?

**Comment by joefitter** [comment]
nope - its hof

**Comment by joefitter** [comment]
just 2 of us, as they aren't using hof (yet)

**Comment by joefitter** [comment]
🎉

**Comment by joefitter** [comment]
could you bump a major and publish please? I don't think I have permissions to publish to npm

**Comment by JoeChapman** [comment]
published version 8.0.0

**Pull request merged**
