### PR TITLE
8.1.0-rc

### PR DESCRIPTION
**Pull request by roc**
### Installs exact versions of `hmpo` dependency list
- uses versions that should allow `8.0.0` users to transition to `8.1.0` without errors
- updates and pins `hmpo-template-mixins` to `4.3.0`
- these were the versions that allowed me to run our current master branch of [evw-self-serve](https://github.com/UKHomeOffice/evw-self-serve) without errors, but with new [styling changes](https://github.com/UKHomeOffice/passports-template-mixins/pull/65) from `hmpo-template-mixins`

As a note on the pinning policies in `hof`, I'd be keen for all future releases to come with _exact_ package numbers in the `package.json` file as well as the bundled `npm-shrinkwrap.json`.
- Having the exact packages in `package.json` is explicit and allows us to know what we _should_ be getting
- Having the shrinkwrap file allows you to have confidence in all sub-packages
### Update to 8.1.0
- Changelog updated accordingly

### CODE REVIEW

**Comment by roc** [comment]
I can't find a v8 branch/tag to merge into so this is open against master, if someone could give me another route in I'd be quite happy

**Comment by easternbloc** [comment]
Btw the pinning is largely `my hair is a bird` as we ship shrinkwrap. Adding the shrinkwrap means it can't update from those versions anyway.

**Comment by easternbloc** [comment]
@roc in case you needed telling http://i1.kym-cdn.com/entries/icons/original/000/000/185/nickcage.jpeg

**Comment by roc** [comment]
@easternbloc thanks that's really cleared things up for me here

**Comment by easternbloc** [comment]
@roc I think nick cage clears things up for everyone

**Comment by easternbloc** [comment]
@roc I've pushed release/v8 as a branch for you. You should be able to make a PR into that and then we can do an npm publish from there.

**Pull request closed without merging**
