### PR TITLE
Adding snyk

### PR DESCRIPTION
**Pull request by easternbloc**
This checks for known vunerable packages and should probably be added to ensure we are publishing safe releases

### CODE REVIEW

**Comment by daniel-ac-martin** [comment]
@easternbloc: Perhaps we should also  make a PR for this on i18n-future?

**Comment by easternbloc** [comment]
@daniel-ac-martin if you do it I can merge it :)

**Comment by daniel-ac-martin** [comment]
Or will this cover that for us?

**Comment by easternbloc** [comment]
@daniel-ac-martin it'll go through sub modules for us but it's not gonna do any harm

**Comment by JoeChapman** [comment]
Better fix those vulnerabilities first

**Comment by easternbloc** [comment]
@JoeChapman it was more a show the problems thing. I knew it'd fail at this point

**Comment by JoeChapman** [comment]
Yeh, that's fine, but it still fails the build, so presumably this can't be merged, right?

**Comment by daniel-ac-martin** [comment]
If we can make this fly it could provide quite a lot of value to projects. Could almost have "security" as one of HOF's selling points. ;-)

**Comment by easternbloc** [comment]
@JoeChapman 

I'll leave it here as a prod that we need to address these issues.

**Pull request closed without merging**
