### PR TITLE
Update packages and shrinkwrap

### PR DESCRIPTION
**Pull request by JoeChapman**
- update hof-controller@v1.0.2
- update hmpo-frontend-toolkit@^5.0.0
- save eslint-config-homeoffice in devDeps
- shrinkwrap the lot

### CODE REVIEW

**Comment by joefitter** [comment]
_**THIS PULL REQUEST LOOKS GOOD TO ME**_

**Comment by joefitter** [comment]
@JoeChapman could I be a massive **_pain_** and ask that hof-controllers 1.0.3 is included in this? It would make me happy.

**Comment by joefitter** [comment]
@easternbloc @daniel-ac-martin @JoeChapman LGTM

**Comment by gavboulton** [comment]
The major version bump to hmpo-frontend-toolkit is incompatible with the current version of hmpo-template-mixins. I don't know the full extent until I have a proper look but one example is `class="panel-indent"` changing to `class="panel panel-border-wide"`. There will probably be some overrides that need removing.

**Comment by joefitter** [comment]
@JoeChapman we should update this PR to point to the last compatible version of hmpo-frontend-toolkit - @gavboulton is this `4.2.0`? We should also bump hmpo-form-controller to latest version `0.8.1` and wait for https://github.com/UKHomeOffice/passports-form-wizard/pull/65 to be merged and bumped to fix the current issue with step invalidation when editing a form.

**Comment by joefitter** [comment]
@JoeChapman @gxxm @easternbloc @daniel-ac-martin @bendiggle ^ please

**Comment by JoeChapman** [comment]
@easternbloc @daniel-ac-martin how are you feeling about this pull request now, any problems?

**Pull request closed without merging**
