### PR TITLE
Adding missing files

### PR DESCRIPTION
**Pull request by ipedrazas**
Contributing, travis and license.

### CODE REVIEW

**Comment by PurpleBooth** [comment]
lgtm

**Comment by easternbloc** [comment]
Hi, sorry to be a pain but as these are three separate things they should either be 3 PRs or at the least 3 commits.

We also follow GPLv2 not v3

And in terms of a contributing file we'd like to base it off this one as we're quite keen for the style guides to be followed from there: https://github.com/UKHomeOffice/brp_app/blob/master/CONTRIBUTING.md

**Comment by ipedrazas** [comment]
@easternbloc you're right with the 3 PRs :(

What's not clear is why you want to explicitly follow GPLv2... usually, GPL licenses cover "any later version" (of the license).

Is there a reason for following strictly v2?

**Comment by easternbloc** [comment]
@ipedrazas when I asked the overlords what license should we use I was explicitly told GPLv2. So I have no idea really... Department wide I know we're publishing under GPL are you guys just going to v3? I'd rather follow what the majority are doing.

**Comment by ipedrazas** [comment]
`overlords` :smile: 

I'll update to v2, it's not a problem, I just wanted to know if there was a requirement.

**Comment by PurpleBooth** [comment]
@ipedrazas This can probably be closed now, as the only thing missing is some sort of CI, and as this is a meta package that is probably not useful.

**Comment by easternbloc** [comment]
Thanks for the reminder @PurpleBooth going to close this. Thanks for the PR :)

**Pull request closed without merging**
