### PR TITLE
Update shrinkwrap

### PR DESCRIPTION
**Pull request by JoeChapman**
- update shrinkwrap with latest version of hof-controllers (v1.0.2)
- save eslint-config-homeoffice

### CODE REVIEW

**Comment by JoeChapman** [comment]
@easternbloc

**Comment by easternbloc** [comment]
Umm, this is somewhat out of date now we've unpublished 9.0.0 you'll need to make a new commit with a version bump and a new shrinkwrap

**Comment by easternbloc** [comment]
And maybe as part of 9 we should be fixing sync and also adding the new frontend toolkit and template mixins

https://github.com/UKHomeOffice/passports-template-mixins

and

https://github.com/UKHomeOffice/passports-frontend-toolkit

**Comment by JoeChapman** [comment]
> Umm, this is somewhat out of date now we've unpublished 9.0.0 you'll need to make a new commit with a version bump and a new shrinkwrap

It doesn't _need_ to be bumped just yet. The shrinkwrapis just an update to its deps, that we can make use of during development

**Pull request closed without merging**
